# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DENNOU TECH BLOG
email: dennoukoei@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  技術情報やプログラミングのヒントを共有する技術ブログです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dennoukoei
github_username:  dennoukoei

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Minimal Mistakes settings
locale: "ja-JP"
name: "Dennou Koei"
search: true

# Site Author
author:
  name             : "電脳狐影"
  avatar           : "https://avatars.githubusercontent.com/u/206489032?v=4"
  bio              : "技術とプログラミングが好きなエンジニア"
  location         : "東京"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:dennoukoei@gmail.com"
    - label: "X (Twitter)"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/dennoukoei"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dennoukoei"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "#"

# サイトフッターのリンク
footer:
  links:
    - label: "X (Twitter)"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/dennoukoei"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dennoukoei"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
